<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SssContributionScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sss_contribution_schedules')->insert([
            [
                'start_range_of_compensation' => 0,
                'end_range_of_compensation' => 5249.99,
                'regular_ss_employees_compensation' => 5000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 500,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 250,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 5250,
                'end_range_of_compensation' => 5749.99,
                'regular_ss_employees_compensation' => 5500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 550,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 275,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 5750,
                'end_range_of_compensation' => 6249.99,
                'regular_ss_employees_compensation' => 6000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 600,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 300,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 6250,
                'end_range_of_compensation' => 6749.99,
                'regular_ss_employees_compensation' => 6500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 650,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 325,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 6750,
                'end_range_of_compensation' => 7249.99,
                'regular_ss_employees_compensation' => 7000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 700,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 350,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 7250,
                'end_range_of_compensation' => 7749.99,
                'regular_ss_employees_compensation' => 7500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 750,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 375,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 750,
                'end_range_of_compensation' => 8249.99,
                'regular_ss_employees_compensation' => 8000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 800,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 400,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 8250,
                'end_range_of_compensation' => 8749.99,
                'regular_ss_employees_compensation' => 8500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 850,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 345,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 8750,
                'end_range_of_compensation' => 9249.99,
                'regular_ss_employees_compensation' => 9000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 900,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 450,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 9250,
                'end_range_of_compensation' => 9749.99,
                'regular_ss_employees_compensation' => 9500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 950,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 475,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 9750,
                'end_range_of_compensation' => 10249.99,
                'regular_ss_employees_compensation' => 10000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1000,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 500,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 10250,
                'end_range_of_compensation' => 10749.99,
                'regular_ss_employees_compensation' => 10500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1050,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 525,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 10750,
                'end_range_of_compensation' => 11249.99,
                'regular_ss_employees_compensation' => 11000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1100,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 550,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 11250,
                'end_range_of_compensation' => 11749.99,
                'regular_ss_employees_compensation' => 11500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1150,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 575,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 11750,
                'end_range_of_compensation' => 12249.99,
                'regular_ss_employees_compensation' => 12000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1200,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 600,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 12250,
                'end_range_of_compensation' => 12749.99,
                'regular_ss_employees_compensation' => 12500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1250,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 625,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 12750,
                'end_range_of_compensation' => 13249.99,
                'regular_ss_employees_compensation' => 13000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1300,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 650,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 13250,
                'end_range_of_compensation' => 13749.99,
                'regular_ss_employees_compensation' => 13500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1350,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 675,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 13750,
                'end_range_of_compensation' => 14249.99,
                'regular_ss_employees_compensation' => 14000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1400,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 700,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 14250,
                'end_range_of_compensation' => 14749.99,
                'regular_ss_employees_compensation' => 14500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1450,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 10,
                'employees_regular_ss_contribution' => 725,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 14750,
                'end_range_of_compensation' => 15249.99,
                'regular_ss_employees_compensation' => 15000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1500,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 750,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 15250,
                'end_range_of_compensation' => 15749.99,
                'regular_ss_employees_compensation' => 15500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1550,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 775,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 15750,
                'end_range_of_compensation' => 16249.99,
                'regular_ss_employees_compensation' => 16000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1600,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 800,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 16250,
                'end_range_of_compensation' => 16749.99,
                'regular_ss_employees_compensation' => 16500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1650,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 825,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 16750,
                'end_range_of_compensation' => 17249.99,
                'regular_ss_employees_compensation' => 17000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1700,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 850,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 17250,
                'end_range_of_compensation' => 17749.99,
                'regular_ss_employees_compensation' => 17500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1750,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 875,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 17750,
                'end_range_of_compensation' => 18249.99,
                'regular_ss_employees_compensation' => 18000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1800,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 900,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 18250,
                'end_range_of_compensation' => 18749.99,
                'regular_ss_employees_compensation' => 18500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1850,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 925,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 18750,
                'end_range_of_compensation' => 19249.99,
                'regular_ss_employees_compensation' => 19000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1900,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 950,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 19250,
                'end_range_of_compensation' => 19749.99,
                'regular_ss_employees_compensation' => 19500,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 1950,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 975,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 19750,
                'end_range_of_compensation' => 20249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => null,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => null,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 20250,
                'end_range_of_compensation' => 20749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 50,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 25,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 20750,
                'end_range_of_compensation' => 21249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 1000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 100,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 50,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 21250,
                'end_range_of_compensation' => 21749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 1500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 150,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 75,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 21750,
                'end_range_of_compensation' => 22249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 2000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 200,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 100,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 22250,
                'end_range_of_compensation' => 22749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 2500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 250,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 125,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 22750,
                'end_range_of_compensation' => 23249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 3000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 300,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 150,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 23250,
                'end_range_of_compensation' => 23749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 3500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 350,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 175,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 23750,
                'end_range_of_compensation' => 23749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 4000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 400,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 200,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 24250,
                'end_range_of_compensation' => 24749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 4500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 40,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 225,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 24750,
                'end_range_of_compensation' => 24749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 5000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 500,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 250,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 25250,
                'end_range_of_compensation' => 25749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 5500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 550,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 275,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 25750,
                'end_range_of_compensation' => 25749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 6000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 600,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 300,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 26250,
                'end_range_of_compensation' => 26749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 6500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 650,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 325,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 26750,
                'end_range_of_compensation' => 26749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 7000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 700,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 350,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 27250,
                'end_range_of_compensation' => 27749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 7500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 750,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 375,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 27750,
                'end_range_of_compensation' => 28249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 8000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 800,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 400,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 28250,
                'end_range_of_compensation' => 28749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 8500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 850,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 425,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 28750,
                'end_range_of_compensation' => 29249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 9000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 900,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 450,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 29250,
                'end_range_of_compensation' => 29749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 9500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 950,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 475,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 29750,
                'end_range_of_compensation' => 30249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 10000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1000,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 500,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 30250,
                'end_range_of_compensation' => 30749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 10500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1050,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 525,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 30750,
                'end_range_of_compensation' => 31249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 11000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1100,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 550,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 31250,
                'end_range_of_compensation' => 31749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 11500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1150,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 575,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 31750,
                'end_range_of_compensation' => 32249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 12000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1200,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 600,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 32250,
                'end_range_of_compensation' => 32749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 12500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1250,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 625,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 32750,
                'end_range_of_compensation' => 33249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 13000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1300,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 650,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 33250,
                'end_range_of_compensation' => 33749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 13500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1350,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 675,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 33750,
                'end_range_of_compensation' => 34249.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 14000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1400,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 700,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 34250,
                'end_range_of_compensation' => 34749.99,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 14500,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1450,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 725,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'start_range_of_compensation' => 34750,
                'end_range_of_compensation' => null,
                'regular_ss_employees_compensation' => 20000,
                'mandatory_provident_fund' => 15000,
                'employer_regular_ss_contribution' => 2000,
                'employer_mpf_contribution' => 1500,
                'employees_compensation' => 30,
                'employees_regular_ss_contribution' => 1000,
                'employees_mpf_contribution' => 750,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
