<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Discount extends Model
{
    use HasFactory;
    protected $fillable = [
        'code','title','type','is_amount','price','amount','percent','client_id','sales_id','date_claimed','sales_id_claimed'
    ];

    protected $appends = ['discount_amount'];

    public function sale(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Sale::class);
    }

    public function client(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function getDiscountAmountAttribute()
    {
        return $this->is_amount ? $this->amount : $this->percent;
    }

    protected static function boot()
    {

        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function($discount){
            $discount->code = self::generateUniqueCode();
        });
        static::creating(function($discount){
            $discount->code = self::generateUniqueCode();
        });
    }

    protected static function generateUniqueCode(): string
    {
        $code = sprintf("%08d", mt_rand(1, 99999999));
        if(DB::table('discounts')->where('code',$code)->count() > 0)
        {
            self::generateUniqueCode();
        }
        return $code;
    }
}
